<?php
/**
 * Innoexts
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the InnoExts Commercial License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://innoexts.com/commercial-license-agreement
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@innoexts.com so we can send you a copy immediately.
 * 
 * @category    Innoexts
 * @package     Innoexts_Warehouse
 * @copyright   Copyright (c) 2013 Innoexts (http://www.innoexts.com)
 * @license     http://innoexts.com/commercial-license-agreement  InnoExts Commercial License
 */
?>

<!-- Warehouse -->
<?php $helper                       = $this->helper('warehouse') ?>
<?php $config                       = $helper->getConfig() ?>

<?php if ($config->isMultipleMode()) : ?>
    <?php if ($config->isSplitOrderEnabled()) : ?>
    <?php echo $this->getMultipleModeHtml() ?>
    <?php else : ?>
    <?php echo $this->getSingleModeHtml() ?>
    <?php endif; ?>
<?php else : ?>
<?php echo $this->getSingleModeHtml() ?>
<?php endif; ?>
